// File generated by FlutterFire CLI would replace this.
// 지금은 프로젝트가 아직 연결되지 않았다. `flutterfire configure` 실행 후 이 파일이 덮어씌워진다.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('웹은 지원하지 않습니다.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'Firebase 설정 파일이 없습니다. README의 flutterfire configure 를 실행하세요.',
        );
      default:
        throw UnsupportedError('지원하지 않는 플랫폼입니다.');
    }
  }
}
